name: Check code styling

on: [push, pull_request]

jobs:
  run-xo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g pnpm
      - run: pnpm i --prefer-frozen-lockfile
      - run: pnpm run test
